import { useEffect, useState } from 'preact/hooks';
import type { ComponentChildren } from 'preact';
import type { AppRoute } from '../navigation/routes';
import { GOAL_CATALOG, type GoalId } from '../domain/goals/goalCatalog';
import { PROTOCOL_CATALOG } from '../domain/protocols/protocolCatalog';
import { createBook } from '../domain/books/bookLifecycle';
import type { Book } from '../domain/books/book';
import { createBookRepository, createProtocolSnapshotRepository, createReadingPlanRepository, createSessionRepository, saveReadingPlanAndSnapshot } from '../storage/indexedDb/domainRepositories';
import { createReadingPlan } from '../domain/planning/createReadingPlan';
import type { ReadingPlan } from '../domain/planning/readingPlan';
import type { ProtocolSnapshot } from '../domain/protocols/protocolSnapshot';
import type { Session } from '../domain/sessions/session';
import { transitionSession } from '../domain/sessions/sessionStateMachine';
import { startTimer, tickTimer, remainingTimerMs, type TimerState } from '../domain/timer/absoluteTimer';

interface FlowProps { readonly route: AppRoute; }
function createId(): string { return globalThis.crypto?.randomUUID?.() ?? `local-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function FlowLayout({ title, description, children }: { title: string; description: string; children?: ComponentChildren }) { return <div class="screen-root flow-screen"><header class="app-bar"><div><h1 class="page-title">{title}</h1><p class="supporting-text">{description}</p></div><a class="text-action" href="#/library">المكتبة</a></header>{children}</div>; }
function Failure({ message }: { message: string }) { return <p class="save-error" role="alert">{message}</p>; }

export function NewBookScreen() {
  const [title, setTitle] = useState(''); const [author, setAuthor] = useState(''); const [pages, setPages] = useState(''); const [status, setStatus] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const valid = title.trim().length > 0 && Number.isInteger(Number(pages)) && Number(pages) > 0;
  async function submit(event: SubmitEvent) { event.preventDefault(); if (!valid || saving) return; setSaving(true); setStatus(null); try { const book = await createBook({ title, author: author || undefined, totalPages: Number(pages) }, { repository: createBookRepository(), createId, now: () => new Date().toISOString() }); window.location.hash = `#/books/${encodeURIComponent(book.id)}/goals`; } catch { setStatus('تعذر حفظ الكتاب محليًا. لم تتغير البيانات؛ حاول مرة أخرى.'); } finally { setSaving(false); } }
  return <FlowLayout title="كتاب جديد" description="احفظ مرجع الكتاب فقط؛ محتوى الملف يبقى خارج الإضافة."><form class="flow-form" onSubmit={submit}><label>عنوان الكتاب<input value={title} onInput={(event) => setTitle((event.currentTarget as HTMLInputElement).value)} required maxLength={200} /></label><label>المؤلف (اختياري)<input value={author} onInput={(event) => setAuthor((event.currentTarget as HTMLInputElement).value)} maxLength={160} /></label><label>عدد الصفحات<input type="number" min="1" max="1000000" value={pages} onInput={(event) => setPages((event.currentTarget as HTMLInputElement).value)} required /></label>{status ? <Failure message={status} /> : <p class="supporting-text">سيُحفظ العنوان والبيانات الوصفية محليًا فقط.</p>}<button class="primary-button" type="submit" disabled={!valid || saving}>{saving ? 'جارٍ الحفظ…' : 'متابعة لاختيار الهدف'}</button></form></FlowLayout>;
}

export function GoalSelectionScreen({ route }: FlowProps) {
  if (route.name !== 'goal-selection') return null;
  const [book, setBook] = useState<Book | null>(null); const [primary, setPrimary] = useState<GoalId>('deep-understanding'); const [secondary, setSecondary] = useState<GoalId[]>([]); const [minutes, setMinutes] = useState('30'); const [deadline, setDeadline] = useState(''); const [status, setStatus] = useState<string | null>(null);
  useEffect(() => { void createBookRepository().get(route.bookId).then(setBook).catch(() => setStatus('تعذر قراءة الكتاب المحلي.')); }, [route.bookId]);
  function toggleSecondary(goal: GoalId) { setSecondary((current) => current.includes(goal) ? current.filter((id) => id !== goal) : current.length < 2 ? [...current, goal] : current); }
  async function submit(event: SubmitEvent) { event.preventDefault(); if (!book) return; setStatus(null); try { const result = await createReadingPlan({ bookId: book.id, primaryGoal: primary, secondaryGoals: secondary, startPage: 0, endPage: book.metadata.totalPages, availableMinutes: Number(minutes), today: new Date().toISOString().slice(0, 10), deadline: deadline || undefined }, { repository: createReadingPlanRepository(), saveSnapshot: async (snapshot) => createProtocolSnapshotRepository().save(snapshot), savePlanAndSnapshot: saveReadingPlanAndSnapshot, createId, now: () => new Date().toISOString() }); window.location.hash = `#/plans/${encodeURIComponent(result.plan.id)}/protocol`; } catch { setStatus('تعذر إنشاء الخطة محليًا. تحقق من الاختيارات وحاول مرة أخرى.'); } }
  return <FlowLayout title="لماذا تقرأ؟" description={book ? `اختر هدفًا لكتاب «${book.metadata.title}».` : 'جارٍ تحميل الكتاب المحلي…'}><form class="flow-form" onSubmit={submit}><fieldset class="goal-list"><legend class="section-heading">الهدف الرئيسي</legend>{GOAL_CATALOG.map((goal) => <label class="choice-row" key={goal.id}><input type="radio" name="primary-goal" value={goal.id} checked={primary === goal.id} onChange={() => setPrimary(goal.id)} />{goal.labelAr}</label>)}</fieldset><fieldset class="goal-list"><legend class="section-heading">أهداف ثانوية (حتى هدفين)</legend>{GOAL_CATALOG.filter((goal) => goal.id !== primary).map((goal) => <label class="choice-row" key={goal.id}><input type="checkbox" checked={secondary.includes(goal.id)} onChange={() => toggleSecondary(goal.id)} />{goal.labelAr}</label>)}</fieldset><label>الدقائق المتاحة يوميًا<input type="number" min="1" value={minutes} onInput={(event) => setMinutes((event.currentTarget as HTMLInputElement).value)} required /></label><label>الموعد النهائي (اختياري)<input type="date" value={deadline} onInput={(event) => setDeadline((event.currentTarget as HTMLInputElement).value)} /></label>{status ? <Failure message={status} /> : null}<button class="primary-button" type="submit" disabled={!book}>إنشاء الخطة وعرض الطريقة</button></form></FlowLayout>;
}

export function ProtocolPreviewScreen({ route }: FlowProps) {
  if (route.name !== 'protocol-preview') return null;
  const [plan, setPlan] = useState<ReadingPlan | null>(null); const [snapshot, setSnapshot] = useState<ProtocolSnapshot | null>(null); const [status, setStatus] = useState<string | null>(null);
  useEffect(() => { void createReadingPlanRepository().get(route.planId).then((loadedPlan) => { if (!loadedPlan) { setStatus('لم نعثر على هذه الخطة المحلية.'); return; } setPlan(loadedPlan); return createProtocolSnapshotRepository().get(loadedPlan.protocolSnapshotId).then((loadedSnapshot) => { if (!loadedSnapshot) setStatus('تعذر العثور على نسخة الطريقة المحفوظة.'); else setSnapshot(loadedSnapshot); }); }).catch(() => setStatus('تعذر قراءة الخطة المحلية.')); }, [route.planId]);
  const protocol = snapshot ? PROTOCOL_CATALOG.find((item) => item.id === snapshot.protocolId) : null;
  return <FlowLayout title="طريقة القراءة" description="هذه النتيجة مبنية على هدفك وتظل ثابتة داخل الخطة.">{status ? <Failure message={status} /> : null}<section class="flow-card">{protocol ? <><h2>{protocol.labelAr}</h2><p>{protocol.referenceName}</p><ol>{snapshot?.steps.map((step) => <li key={step.id}>{step.labelAr}</li>)}</ol></> : <p>جارٍ تحميل الخطة…</p>}</section>{plan ? <button class="primary-button" type="button" onClick={async () => { const session: Session = { schemaVersion: 1, id: createId(), planId: plan.id, status: 'ready', currentStepId: snapshot?.steps[0]?.id ?? 'focus', lastSafeStatus: 'ready', updatedAt: new Date().toISOString() }; await createSessionRepository().save(session); window.location.hash = `#/sessions/${session.id}/focus`; }}>ابدأ الجلسة</button> : null}</FlowLayout>;
}

export function FocusSessionScreen({ route }: FlowProps) {
  if (route.name !== 'focus-session') return null;
  const [timer, setTimer] = useState<TimerState | null>(null);
  useEffect(() => { let active = true; const now = () => new Date().toISOString(); void createSessionRepository().get(route.sessionId).then((session) => { if (!active || !session) return; const started = session.status === 'ready' ? transitionSession(session, 'start', now()) : { ok: true as const, session }; if (!started.ok) return; const nextTimer = startTimer('pomodoro', now(), 25); setTimer(nextTimer); void createSessionRepository().save({ ...started.session, targetEndAt: nextTimer.targetEndAt, accumulatedPausedMs: nextTimer.accumulatedPausedMs }); }); const handle = window.setInterval(() => setTimer((current) => current ? tickTimer(current, now()) : current), 1000); return () => { active = false; window.clearInterval(handle); }; }, [route.sessionId]);
  const seconds = timer ? Math.floor(remainingTimerMs(timer, new Date().toISOString()) / 1000) : 1500; const minutes = Math.floor(seconds / 60).toString().padStart(2, '0'); const remainder = (seconds % 60).toString().padStart(2, '0');
  return <FlowLayout title="جلسة تركيز" description="خطوة واحدة الآن؛ يمكنك الإيقاف والاستكمال بأمان."><section class="timer-card" aria-live="polite"><strong><bdi dir="ltr">{minutes}:{remainder}</bdi></strong><span>{timer?.status === 'expired' ? 'انتهى الوقت — انتقل للاسترجاع' : 'قراءة مركّزة'}</span></section><div class="flow-actions"><a class="primary-button" href={`#/sessions/${encodeURIComponent(route.sessionId)}/review`}>انتقل إلى الاسترجاع</a><button class="text-action" type="button">تشتتُّ — سجّل الحدث</button></div></FlowLayout>;
}
export function RecallReviewScreen({ route }: FlowProps) { if (route.name !== 'recall-review') return null; return <FlowLayout title="استرجع واشرح" description="اكتب ما تتذكره قبل العودة إلى الكتاب."><label>ماذا تتذكر؟<textarea rows={6} /></label><a class="primary-button" href={`#/sessions/${encodeURIComponent(route.sessionId)}/summary`}>احفظ وانتقل للملخص</a></FlowLayout>; }
export function SessionSummaryScreen({ route }: FlowProps) { if (route.name !== 'session-summary') return null; return <FlowLayout title="ملخص الجلسة" description="تحقّق من مخرجاتك قبل إنهاء الجلسة."><section class="flow-card"><h2>خطوة جيدة</h2><p>راجع الاسترجاع وحدد التطبيق التالي.</p></section><a class="primary-button" href="#/library">العودة إلى المكتبة</a></FlowLayout>; }
export function BookProgressScreen({ route }: FlowProps) { if (route.name !== 'book-progress') return null; return <FlowLayout title="تقدم الكتاب" description="هنا ستظهر الجلسات والمواد التعليمية المحفوظة."><section class="flow-card"><p>لا يوجد تقدم محفوظ بعد.</p></section><a class="primary-button" href="#/books/new">أضف جلسة جديدة</a></FlowLayout>; }
