import { useEffect, useRef, useState } from 'preact/hooks';
import type { ComponentChildren } from 'preact';
import { serializeRoute, type AppRoute } from '../navigation/routes';
import { GOAL_CATALOG, type GoalId } from '../domain/goals/goalCatalog';
import { PROTOCOL_CATALOG } from '../domain/protocols/protocolCatalog';
import { archiveBook, createBook, restoreBook } from '../domain/books/bookLifecycle';
import type { Book } from '../domain/books/book';
import { createBookRepository, createDistractionEventRepository, createLearningArtifactRepository, createProtocolSnapshotRepository, createReadingPlanRepository, createSessionRepository, saveReadingPlanAndSnapshot, saveSessionArtifactsBundle, saveSessionBundle } from '../storage/indexedDb/domainRepositories';
import { createReadingPlan } from '../domain/planning/createReadingPlan';
import type { ReadingPlan } from '../domain/planning/readingPlan';
import type { ProtocolSnapshot } from '../domain/protocols/protocolSnapshot';
import type { Session } from '../domain/sessions/session';
import type { SessionStep, LearningArtifact } from '../domain/sessions/sessionRecords';
import { addQuestion, createPreviewQuestionState } from '../domain/sessions/previewQuestions';
import { transitionSession } from '../domain/sessions/sessionStateMachine';
import { createGapArtifact, createLearningArtifact } from '../domain/sessions/learningArtifacts';
import { createDistractionEvent } from '../domain/sessions/distractions';
import { buildSessionSummary } from '../domain/sessions/sessionSummary';
import { createAutosaveCoordinator, type AutosaveStatus } from '../storage/autosave';
import { calculateLearningMetrics, type LearningMetrics } from '../domain/progress/learningMetrics';
import { recommendBookResume, type ResumeRecommendation } from '../domain/progress/resumeRecommendation';
import { METRICS_PRIVACY_NOTICE_AR } from '../domain/progress/metricsPrivacy';
import { downloadExportFile, exportProductData, serializeMarkdownExport, serializeProductExport } from '../storage/indexedDb/dataExport';
import { pauseTimer, resumeTimer, startBreak, startTimer, tickTimer, remainingTimerMs, type TimerState } from '../domain/timer/absoluteTimer';

interface FlowProps { readonly route: AppRoute; }
function createId(): string { return globalThis.crypto?.randomUUID?.() ?? `local-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function FlowLayout({ title, description, children }: { title: string; description: string; children?: ComponentChildren }) { return <div class="screen-root flow-screen"><header class="app-bar"><div><h1 class="page-title">{title}</h1><p class="supporting-text">{description}</p></div><a class="text-action" href="#/library">المكتبة</a></header>{children}</div>; }
function Failure({ message }: { message: string }) { return <p class="save-error" role="alert">{message}</p>; }

export function NewBookScreen() {
  const [title, setTitle] = useState(''); const [author, setAuthor] = useState(''); const [pages, setPages] = useState(''); const [status, setStatus] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const valid = title.trim().length > 0 && Number.isInteger(Number(pages)) && Number(pages) > 0;
  async function submit(event: SubmitEvent) { event.preventDefault(); if (!valid || saving) return; setSaving(true); setStatus(null); try { const book = await createBook({ title, author: author || undefined, totalPages: Number(pages) }, { repository: createBookRepository(), createId, now: () => new Date().toISOString() }); window.location.hash = `#/books/${encodeURIComponent(book.id)}/goals`; } catch { setStatus('تعذر حفظ الكتاب محليًا. لم تتغير البيانات؛ حاول مرة أخرى.'); } finally { setSaving(false); } }
  return <FlowLayout title="كتاب جديد" description="احفظ مرجع الكتاب فقط؛ محتوى الملف يبقى خارج الإضافة."><form class="flow-form" onSubmit={submit}><label>عنوان الكتاب<input value={title} onInput={(event) => setTitle((event.currentTarget as HTMLInputElement).value)} required maxLength={200} /></label><label>المؤلف (اختياري)<input value={author} onInput={(event) => setAuthor((event.currentTarget as HTMLInputElement).value)} maxLength={160} /></label><label>عدد الصفحات<input type="number" min="1" max="1000000" value={pages} onInput={(event) => setPages((event.currentTarget as HTMLInputElement).value)} required /></label>{status ? <Failure message={status} /> : <p class="supporting-text">سيُحفظ العنوان والبيانات الوصفية محليًا فقط.</p>}<button class="primary-button" type="submit" disabled={!valid || saving}>{saving ? 'جارٍ الحفظ…' : 'متابعة لاختيار الهدف'}</button></form></FlowLayout>;
}

export function GoalSelectionScreen({ route }: FlowProps) {
  if (route.name !== 'goal-selection') return null;
  const [book, setBook] = useState<Book | null>(null); const [primary, setPrimary] = useState<GoalId>('deep-understanding'); const [secondary, setSecondary] = useState<GoalId[]>([]); const [minutes, setMinutes] = useState('30'); const [deadline, setDeadline] = useState(''); const [status, setStatus] = useState<string | null>(null);
  useEffect(() => { void createBookRepository().get(route.bookId).then(setBook).catch(() => setStatus('تعذر قراءة الكتاب المحلي.')); }, [route.bookId]);
  function toggleSecondary(goal: GoalId) { setSecondary((current) => current.includes(goal) ? current.filter((id) => id !== goal) : current.length < 2 ? [...current, goal] : current); }
  async function submit(event: SubmitEvent) { event.preventDefault(); if (!book) return; setStatus(null); try { const result = await createReadingPlan({ bookId: book.id, primaryGoal: primary, secondaryGoals: secondary, startPage: 0, endPage: book.metadata.totalPages, availableMinutes: Number(minutes), today: new Date().toISOString().slice(0, 10), deadline: deadline || undefined }, { repository: createReadingPlanRepository(), saveSnapshot: async (snapshot) => createProtocolSnapshotRepository().save(snapshot), savePlanAndSnapshot: saveReadingPlanAndSnapshot, createId, now: () => new Date().toISOString() }); window.location.hash = `#/plans/${encodeURIComponent(result.plan.id)}/protocol`; } catch { setStatus('تعذر إنشاء الخطة محليًا. تحقق من الاختيارات وحاول مرة أخرى.'); } }
  return <FlowLayout title="لماذا تقرأ؟" description={book ? `اختر هدفًا لكتاب «${book.metadata.title}».` : 'جارٍ تحميل الكتاب المحلي…'}><form class="flow-form" onSubmit={submit}><fieldset class="goal-list"><legend class="section-heading">الهدف الرئيسي</legend>{GOAL_CATALOG.map((goal) => <label class="choice-row" key={goal.id}><input type="radio" name="primary-goal" value={goal.id} checked={primary === goal.id} onChange={() => setPrimary(goal.id)} />{goal.labelAr}</label>)}</fieldset><fieldset class="goal-list"><legend class="section-heading">أهداف ثانوية (حتى هدفين)</legend>{GOAL_CATALOG.filter((goal) => goal.id !== primary).map((goal) => <label class="choice-row" key={goal.id}><input type="checkbox" checked={secondary.includes(goal.id)} onChange={() => toggleSecondary(goal.id)} />{goal.labelAr}</label>)}</fieldset><label>الدقائق المتاحة يوميًا<input type="number" min="1" value={minutes} onInput={(event) => setMinutes((event.currentTarget as HTMLInputElement).value)} required /></label><label>الموعد النهائي (اختياري)<input type="date" value={deadline} onInput={(event) => setDeadline((event.currentTarget as HTMLInputElement).value)} /></label>{status ? <Failure message={status} /> : null}<button class="primary-button" type="submit" disabled={!book}>إنشاء الخطة وعرض الطريقة</button></form></FlowLayout>;
}

export function ProtocolPreviewScreen({ route }: FlowProps) {
  if (route.name !== 'protocol-preview') return null;
  const [plan, setPlan] = useState<ReadingPlan | null>(null); const [snapshot, setSnapshot] = useState<ProtocolSnapshot | null>(null); const [status, setStatus] = useState<string | null>(null);
  const [question, setQuestion] = useState(''); const [savedQuestion, setSavedQuestion] = useState(false);
  useEffect(() => { void createReadingPlanRepository().get(route.planId).then((loadedPlan) => { if (!loadedPlan) { setStatus('لم نعثر على هذه الخطة المحلية.'); return; } setPlan(loadedPlan); return createProtocolSnapshotRepository().get(loadedPlan.protocolSnapshotId).then((loadedSnapshot) => { if (!loadedSnapshot) setStatus('تعذر العثور على نسخة الطريقة المحفوظة.'); else setSnapshot(loadedSnapshot); }); }).catch(() => setStatus('تعذر قراءة الخطة المحلية.')); }, [route.planId]);
  const protocol = snapshot ? PROTOCOL_CATALOG.find((item) => item.id === snapshot.protocolId) : null;
  return <FlowLayout title="طريقة القراءة" description="هذه النتيجة مبنية على هدفك وتظل ثابتة داخل الخطة.">{status ? <Failure message={status} /> : null}<section class="flow-card">{protocol ? <><h2>{protocol.labelAr}</h2><p>{protocol.referenceName}</p><ol>{snapshot?.steps.slice(0, 3).map((step) => <li key={step.id}>{step.labelAr}</li>)}</ol></> : <p>جارٍ تحميل الخطة…</p>}</section>{plan ? <form class="flow-form" onSubmit={async (event) => { event.preventDefault(); try { const session: Session = { schemaVersion: 1, id: createId(), planId: plan.id, status: 'ready', currentStepId: snapshot?.steps[0]?.id ?? 'focus', lastSafeStatus: 'ready', pageStart: plan.startPage, pageEnd: plan.endPage, updatedAt: new Date().toISOString() }; const preview = createPreviewQuestionState(snapshot?.steps.map((step) => step.labelAr) ?? []); const withQuestion = question.trim() ? addQuestion(preview, question) : preview; const step: SessionStep = { schemaVersion: 1, id: createId(), sessionId: session.id, stepId: session.currentStepId, order: 1, status: 'active', updatedAt: session.updatedAt }; const artifact = withQuestion.questions[0] ? createLearningArtifact({ id: createId(), sessionId: session.id, type: 'question', content: withQuestion.questions[0], createdAt: session.updatedAt, metadata: { kind: 'question' } }) : undefined; await saveSessionBundle(session, step, artifact); setSavedQuestion(Boolean(artifact)); window.location.hash = `#/sessions/${session.id}/focus`; } catch { setStatus('تعذر حفظ المعاينة محليًا. حاول مرة أخرى.'); } }}><label>سؤال موجّه قبل القراءة (اختياري)<textarea rows={3} value={question} onInput={(event) => setQuestion((event.currentTarget as HTMLTextAreaElement).value)} /></label>{savedQuestion ? <p class="supporting-text" role="status">تم الحفظ محليًا.</p> : null}<button class="primary-button" type="submit">ابدأ الجلسة</button></form> : null}</FlowLayout>;
}

export function FocusSessionScreen({ route }: FlowProps) {
  if (route.name !== 'focus-session') return null;
  const sessionId = route.sessionId;
  const [timer, setTimer] = useState<TimerState | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [note, setNote] = useState('');
  const [question, setQuestion] = useState('');
  const [saveStatus, setSaveStatus] = useState<AutosaveStatus>('saved');
  const [distractionCount, setDistractionCount] = useState(0);
  const artifactIds = useRef<Record<'note' | 'question', string>>({ note: '', question: '' });
  const autosaves = useRef<Record<'note' | 'question', ReturnType<typeof createAutosaveCoordinator<LearningArtifact>> | null>>({ note: null, question: null });
  useEffect(() => { let active = true; const now = () => new Date().toISOString(); void createSessionRepository().get(route.sessionId).then((session) => { if (!active || !session) return; const started = session.status === 'ready' ? transitionSession(session, 'start', now()) : { ok: true as const, session }; if (!started.ok) return; const nextTimer = startTimer('pomodoro', now(), 25); setTimer(nextTimer); void createSessionRepository().save({ ...started.session, targetEndAt: nextTimer.targetEndAt, accumulatedPausedMs: nextTimer.accumulatedPausedMs }); }); const handle = window.setInterval(() => setTimer((current) => current ? tickTimer(current, now()) : current), 1000); return () => { active = false; window.clearInterval(handle); }; }, [route.sessionId]);
  useEffect(() => { let active = true; void Promise.all([createLearningArtifactRepository().listForSession(sessionId), createDistractionEventRepository().listForSession(sessionId)]).then(([artifacts, distractions]) => { if (!active) return; const savedNote = artifacts.find((artifact) => artifact.type === 'explanation' && artifact.metadata?.kind === 'note'); const savedQuestion = artifacts.find((artifact) => artifact.type === 'question'); if (savedNote) { artifactIds.current.note = savedNote.id; setNote(savedNote.content); } if (savedQuestion) { artifactIds.current.question = savedQuestion.id; setQuestion(savedQuestion.content); } setDistractionCount(distractions.length); }).catch(() => setSaveStatus('failed')); return () => { active = false; }; }, [sessionId]);
  const seconds = timer ? Math.floor(remainingTimerMs(timer, new Date().toISOString()) / 1000) : 1500; const minutes = Math.floor(seconds / 60).toString().padStart(2, '0'); const remainder = (seconds % 60).toString().padStart(2, '0');
  async function updateTimer(nextTimer: TimerState, command: 'pause' | 'resume' | 'break') {
    try { const repository = createSessionRepository(); const session = await repository.get(sessionId); if (!session) throw new Error('missing-session'); const next = command === 'pause' ? transitionSession(session, 'pause', new Date().toISOString()) : command === 'resume' ? transitionSession(session, 'resume', new Date().toISOString()) : transitionSession(session, 'start-break', new Date().toISOString()); if (!next.ok) throw new Error(next.error.messageAr); await repository.save({ ...next.session, targetEndAt: nextTimer.targetEndAt, pausedAt: nextTimer.pausedAt, accumulatedPausedMs: nextTimer.accumulatedPausedMs, breakStartedAt: nextTimer.breakStartedAt, breakEndAt: nextTimer.breakEndAt }); setTimer(nextTimer); setActionError(null); } catch { setActionError('تعذر حفظ حالة المؤقت محليًا. حاول مرة أخرى.'); }
  }
  async function saveArtifact(type: 'note' | 'question', content: string) {
    const normalized = content.trim();
    if (!normalized) return;
    const repository = createLearningArtifactRepository();
    const session = await createSessionRepository().get(sessionId);
    if (!session) throw new Error('missing-session');
    const artifactType = type === 'note' ? 'explanation' : 'question';
    const id = artifactIds.current[type] || createId();
    artifactIds.current[type] = id;
    const artifact = createLearningArtifact({ id, sessionId, type: artifactType, content: normalized, createdAt: session.updatedAt, metadata: type === 'note' ? { kind: 'note' } : { kind: 'question' } });
    if (!autosaves.current[type]) autosaves.current[type] = createAutosaveCoordinator(async (value) => repository.save(value));
    const result = await autosaves.current[type]!.save(artifact);
    setSaveStatus(result.status);
  }
  async function recordDistraction() {
    try {
      const session = await createSessionRepository().get(sessionId);
      if (!session) throw new Error('missing-session');
      const event = createDistractionEvent({ id: createId(), sessionId, stepId: session.currentStepId, occurredAt: new Date().toISOString() });
      await createDistractionEventRepository().save(event);
      setDistractionCount((count) => count + 1);
    } catch {
      setActionError('تعذر حفظ حدث التشتت؛ لم تتغير حالة المؤقت.');
    }
  }
  return <FlowLayout title="جلسة تركيز" description="خطوة واحدة الآن؛ يمكنك الإيقاف والاستكمال بأمان."><section class="timer-card" aria-live="polite"><strong><bdi dir="ltr">{minutes}:{remainder}</bdi></strong><span>{timer?.status === 'expired' ? 'انتهى الوقت — انتقل للاسترجاع' : timer?.status === 'break' ? 'استراحة' : 'قراءة مركّزة'}</span></section>{actionError ? <Failure message={actionError} /> : null}<section class="flow-card capture-card"><h2>ملاحظات سريعة</h2><label>ملاحظة (اختياري)<textarea rows={3} value={note} onInput={(event) => setNote((event.currentTarget as HTMLTextAreaElement).value)} onBlur={() => void saveArtifact('note', note).catch(() => setSaveStatus('failed'))} /></label><label>سؤال للعودة إليه<textarea rows={2} value={question} onInput={(event) => setQuestion((event.currentTarget as HTMLTextAreaElement).value)} onBlur={() => void saveArtifact('question', question).catch(() => setSaveStatus('failed'))} /></label><p class="supporting-text" role="status">{saveStatus === 'pending' ? 'جارٍ الحفظ…' : saveStatus === 'retryable' || saveStatus === 'failed' ? 'تعذر الحفظ؛ النص محفوظ في الشاشة، حاول مرة أخرى.' : 'يُحفظ محليًا فقط.'}</p></section><section class="flow-card distraction-card"><h2>تشتت أثناء القراءة</h2><p>سجّل الحدث دون إيقاف المؤقت. العدد الحالي: {distractionCount}</p><button class="text-action" type="button" onClick={() => void recordDistraction()}>سجّل تشتتًا</button></section><div class="flow-actions">{timer?.status === 'running' ? <><button class="primary-button" type="button" onClick={() => { if (timer) void updateTimer(pauseTimer(timer, new Date().toISOString()), 'pause'); }}>إيقاف مؤقت</button><button class="text-action" type="button" onClick={() => { if (timer) void updateTimer(startBreak(timer, new Date().toISOString(), 5), 'break'); }}>ابدأ استراحة</button></> : timer?.status === 'paused' ? <button class="primary-button" type="button" onClick={() => { if (timer) void updateTimer(resumeTimer(timer, new Date().toISOString()), 'resume'); }}>استئناف القراءة</button> : <a class="primary-button" href={`#/sessions/${encodeURIComponent(route.sessionId)}/review`}>انتقل إلى الاسترجاع</a>}</div></FlowLayout>;
}
export function RecallReviewScreen({ route }: FlowProps) {
  if (route.name !== 'recall-review') return null;
  const [content, setContent] = useState(''); const [status, setStatus] = useState<string | null>(null);
  useEffect(() => { void createSessionRepository().get(route.sessionId).then((session) => { if (session?.status === 'active') { const next = transitionSession(session, 'to-recall', new Date().toISOString()); if (next.ok) void createSessionRepository().save(next.session); } }).catch(() => setStatus('تعذر فتح الجلسة المحلية.')); }, [route.sessionId]);
  return <FlowLayout title="استرجع واشرح" description="اكتب ما تتذكره قبل العودة إلى الكتاب."><form class="flow-form" onSubmit={async (event) => { event.preventDefault(); if (!content.trim()) { setStatus('اكتب ما تتذكره قبل المتابعة.'); return; } try { const repository = createSessionRepository(); const session = await repository.get(route.sessionId); if (!session) throw new Error('missing-session'); const review = transitionSession(session, 'to-review', new Date().toISOString()); if (!review.ok) throw new Error(review.error.messageAr); const artifact = createLearningArtifact({ id: createId(), sessionId: session.id, type: 'recall', content, createdAt: review.session.updatedAt }); const step: SessionStep = { schemaVersion: 1, id: createId(), sessionId: session.id, stepId: session.currentStepId, order: 2, status: 'completed', updatedAt: review.session.updatedAt }; await saveSessionArtifactsBundle(review.session, [step], [artifact]); window.location.hash = `#/sessions/${encodeURIComponent(route.sessionId)}/summary`; } catch { setStatus('تعذر حفظ الاسترجاع محليًا. حاول مرة أخرى.'); } }}><label>ماذا تتذكر؟<textarea rows={6} value={content} onInput={(event) => setContent((event.currentTarget as HTMLTextAreaElement).value)} required /></label>{status ? <Failure message={status} /> : null}<button class="primary-button" type="submit">احفظ وانتقل للملخص</button></form></FlowLayout>;
}
export function SessionSummaryScreen({ route }: FlowProps) {
  if (route.name !== 'session-summary') return null;
  const [session, setSession] = useState<Session | null>(null); const [summary, setSummary] = useState<ReturnType<typeof buildSessionSummary> | null>(null); const [review, setReview] = useState(''); const [application, setApplication] = useState(''); const [gap, setGap] = useState(''); const [completed, setCompleted] = useState(false); const [status, setStatus] = useState<string | null>(null);
  useEffect(() => { let active = true; void Promise.all([createSessionRepository().get(route.sessionId), createLearningArtifactRepository().listForSession(route.sessionId), createDistractionEventRepository().listForSession(route.sessionId)]).then(([loadedSession, artifacts, distractions]) => { if (!active || !loadedSession) throw new Error('missing-session'); setSession(loadedSession); setSummary(buildSessionSummary(loadedSession, artifacts, distractions)); setCompleted(loadedSession.status === 'completed'); }).catch(() => { if (active) setStatus('تعذر قراءة مخرجات الجلسة محليًا.'); }); return () => { active = false; }; }, [route.sessionId]);
 async function completeSession(event: SubmitEvent) { event.preventDefault(); if (!session || !review.trim() || !application.trim()) { setStatus('أكمل المراجعة والتطبيق قبل إنهاء الجلسة.'); return; } try { const now = new Date().toISOString(); const result = session.status === 'review' ? transitionSession(session, 'complete', now) : { ok: true as const, session }; if (!result.ok) throw new Error(result.error.messageAr); const artifacts = [createLearningArtifact({ id: createId(), sessionId: session.id, type: 'review', content: review, createdAt: now }), createLearningArtifact({ id: createId(), sessionId: session.id, type: 'application', content: application, createdAt: now }), ...(gap.trim() ? [createGapArtifact({ id: createId(), sessionId: session.id, content: gap, createdAt: now })] : [])]; await saveSessionArtifactsBundle(result.session, [], artifacts); const [savedArtifacts, savedDistractions] = await Promise.all([createLearningArtifactRepository().listForSession(session.id), createDistractionEventRepository().listForSession(session.id)]); setSession(result.session); setSummary(buildSessionSummary(result.session, savedArtifacts, savedDistractions)); setCompleted(true); setStatus(null); } catch { setStatus('تعذر إنهاء الجلسة محليًا. بياناتك محفوظة؛ حاول مرة أخرى.'); } }
  return <FlowLayout title="ملخص الجلسة" description="تحقّق من مخرجاتك قبل إنهاء الجلسة.">{status ? <Failure message={status} /> : null}<section class="flow-card"><h2>{completed ? 'تم حفظ الجلسة' : 'مخرجاتك محفوظة'}</h2><p>الاسترجاع: {summary?.recall.length ?? 0} · الفجوات المفتوحة: {summary?.openGaps.length ?? 0} · التطبيقات: {summary?.applications.length ?? 0}</p><p>التشتت: {summary?.distractionCount ?? 0} حدثًا</p></section>{!completed ? <form class="flow-form" onSubmit={completeSession}><label>ما الذي راجعته؟<textarea rows={4} value={review} onInput={(event) => setReview((event.currentTarget as HTMLTextAreaElement).value)} required /></label><label>ما التطبيق التالي؟<textarea rows={4} value={application} onInput={(event) => setApplication((event.currentTarget as HTMLTextAreaElement).value)} required /></label><label>فجوة فهم (اختياري)<textarea rows={3} value={gap} onInput={(event) => setGap((event.currentTarget as HTMLTextAreaElement).value)} /></label><button class="primary-button" type="submit">إنهاء الجلسة وحفظ الملخص</button></form> : null}<a class="primary-button" href="#/library">العودة إلى المكتبة</a></FlowLayout>;
}
export function BookProgressScreen({ route }: FlowProps) {
  if (route.name !== 'book-progress') return null;
  const [book, setBook] = useState<Book | null>(null); const [status, setStatus] = useState<string | null>(null); const [metrics, setMetrics] = useState<LearningMetrics | null>(null); const [recommendation, setRecommendation] = useState<ResumeRecommendation | null>(null);
  const repository = createBookRepository();
  useEffect(() => { let active = true; void Promise.all([repository.get(route.bookId), createReadingPlanRepository().listForBook(route.bookId), createSessionRepository().list(), createLearningArtifactRepository().list(), createDistractionEventRepository().list()]).then(([loadedBook, plans, sessions, artifacts, distractions]) => { if (!active || !loadedBook) throw new Error('missing-book'); setBook(loadedBook); setMetrics(calculateLearningMetrics({ book: loadedBook, plans, sessions, artifacts, distractions })); setRecommendation(recommendBookResume(loadedBook, plans.find((plan) => plan.status === 'active') ?? plans[0] ?? null, sessions)); }).catch(() => { if (active) setStatus('تعذر قراءة التقدم المحلي.'); }); return () => { active = false; }; }, [route.bookId]);
  async function toggleArchive() { if (!book) return; try { const next = book.archivedAt ? await restoreBook(book, { repository, createId, now: () => new Date().toISOString() }) : await archiveBook(book, { repository, createId, now: () => new Date().toISOString() }); setBook(next); } catch { setStatus('تعذر تحديث حالة الكتاب محليًا.'); } }
  return <FlowLayout title="تقدم الكتاب" description={book ? book.metadata.title : 'جارٍ التحميل…'}>{status ? <Failure message={status} /> : null}<section class="flow-card"><h2>التقدم المحلي</h2><div class="metric-grid"><p><strong>{metrics?.completionRate ?? 0}%</strong><span>إكمال الجلسات</span></p><p><strong>{metrics?.recallCount ?? 0}</strong><span>استرجاع</span></p><p><strong>{metrics?.openGapCount ?? 0}</strong><span>فجوات مفتوحة</span></p><p><strong>{metrics?.applicationCount ?? 0}</strong><span>تطبيقات</span></p></div><p>{recommendation?.messageAr ?? 'لا يوجد تقدم محفوظ بعد.'}</p>{recommendation && recommendation.reason !== 'book-progress' ? <a class="text-action" href={serializeRoute(recommendation.route)}>الخطوة التالية</a> : null}<button class="text-action" type="button" onClick={toggleArchive}>{book?.archivedAt ? 'استعادة الكتاب' : 'أرشفة الكتاب'}</button></section><aside class="privacy-note" aria-label="خصوصية المؤشرات"><p>{METRICS_PRIVACY_NOTICE_AR}</p></aside><a class="primary-button" href="#/books/new">أضف جلسة جديدة</a></FlowLayout>;
}
