$ErrorActionPreference = 'Stop'

$sharedStyle = @'
<style>
*{box-sizing:border-box}body{margin:0;background:#eef2ff;color:#17213a;font-family:Arial,"Segoe UI",sans-serif;direction:rtl}.app{width:460px;min-height:760px;margin:0 auto;background:#f8fafc;padding:24px;display:flex;flex-direction:column;gap:18px}.top{display:flex;justify-content:space-between;align-items:center}.brand{font-size:20px;font-weight:800;color:#3157d5}.muted{color:#64748b;font-size:14px}.card{background:white;border:1px solid #dbe2ee;border-radius:18px;padding:18px;box-shadow:0 8px 24px #17213a10}.hero{background:linear-gradient(145deg,#3157d5,#7c3aed);color:white;border-radius:22px;padding:24px}.hero h1{font-size:30px;margin:0 0 10px}.hero p{line-height:1.7;margin:0}.btn{display:block;text-align:center;text-decoration:none;background:#3157d5;color:white;padding:15px;border-radius:14px;font-weight:800;border:0}.btn.alt{background:white;color:#3157d5;border:2px solid #c7d2fe}.btn.warn{background:#fff1f2;color:#be123c;border:1px solid #fecdd3}.field{background:white;border:1px solid #cbd5e1;border-radius:12px;padding:13px;margin-top:8px;color:#64748b}.label{font-size:14px;font-weight:700;margin-top:10px}.choice{padding:13px;border:1px solid #dbe2ee;border-radius:12px;background:white;margin-top:8px}.choice.on{border-color:#3157d5;background:#eef2ff}.row{display:flex;gap:10px}.row>*{flex:1}.progress{height:10px;background:#e2e8f0;border-radius:10px;overflow:hidden}.progress span{display:block;height:100%;background:#16a085}.metric{font-size:28px;font-weight:800}.step{border-right:4px solid #cbd5e1;padding:8px 14px;margin:8px 0}.step.on{border-color:#16a085;background:#ecfdf5}.timer{text-align:center;font-size:58px;font-weight:800;color:#0f766e}.spacer{flex:1}.success{background:#ecfdf5;border-color:#a7f3d0}.danger{background:#fff1f2;border-color:#fecdd3}textarea{width:100%;height:105px;border:1px solid #cbd5e1;border-radius:12px;padding:12px;font:inherit;direction:rtl}a:focus,button:focus,input:focus,textarea:focus{outline:4px solid #fbbf24;outline-offset:2px}
</style>
'@

$screens = @(
@{File='01-onboarding.html';Title='البداية';Body=@'
<div class="app"><div class="top"><span class="brand">معين</span><span class="muted">محلي وآمن</span></div><div class="hero"><h1>اقرأ بتركيز.<br>تذكّر أكثر.</h1><p>جلسات موجهة بجانب قارئ PDF، من دون رفع كتابك أو إنشاء حساب.</p></div><div class="card"><b>خصوصيتك جزء من المنتج</b><p>الكتب والخطط والجلسات تبقى على جهازك. يمكنك التصدير أو الحذف في أي وقت.</p></div><div class="spacer"></div><a class="btn" href="02-library.html">ابدأ الآن</a><a class="btn alt" href="10-settings.html">إعدادات الوصول</a></div>
'@},
@{File='02-library.html';Title='المكتبة';Body=@'
<div class="app"><div class="top"><span class="brand">مكتبتي</span><a class="muted" href="10-settings.html">الإعدادات</a></div><div class="hero"><h1>مساء الخير</h1><p>جلستك التالية جاهزة عندما تكون أنت جاهزاً.</p></div><div class="card"><b>Clean Architecture</b><p class="muted">التالي: صفحة 124 • Deep Technical</p><div class="progress"><span style="width:35%"></span></div><p><b>35%</b> مكتمل</p><a class="btn" href="06-session.html">متابعة الجلسة</a></div><div class="card"><b>Designing Data-Intensive Applications</b><p class="muted">آخر نشاط: أمس • 12%</p></div><div class="spacer"></div><a class="btn alt" href="03-new-book.html">+ إضافة كتاب</a></div>
'@},
@{File='03-new-book.html';Title='كتاب جديد';Body=@'
<div class="app"><div class="top"><a class="muted" href="02-library.html">رجوع</a><span class="brand">كتاب جديد</span></div><div><div class="label">عنوان الكتاب *</div><div class="field">Clean Architecture</div><div class="label">المؤلف</div><div class="field">Robert C. Martin</div><div class="label">إجمالي الصفحات *</div><div class="field">350</div><div class="label">مرجع PDF اختياري</div><div class="field">عنوان التبويب الحالي</div></div><div class="card"><b>لن نقرأ محتوى الملف</b><p class="muted">نحتفظ فقط بالبيانات التي تدخلها والتقدم الذي تسجله.</p></div><div class="spacer"></div><a class="btn" href="04-goals.html">حفظ واختيار الهدف</a></div>
'@},
@{File='04-goals.html';Title='الهدف والقيود';Body=@'
<div class="app"><div class="top"><a class="muted" href="03-new-book.html">رجوع</a><span class="brand">الهدف</span></div><div><h2>لماذا تقرأ هذا الكتاب؟</h2><div class="choice on">● فهم عميق للمفاهيم</div><div class="choice">○ الاستعداد لامتحان</div><div class="choice">○ تطبيق عملي</div><div class="choice">○ الإنهاء قبل موعد</div><div class="label">الوقت اليومي</div><div class="field">30 دقيقة</div><div class="label">موعد نهائي</div><div class="field">اختياري</div><div class="label">وتيرة مريحة</div><div class="field">متوسطة • 4 صفحات / 10 دقائق</div></div><div class="spacer"></div><a class="btn" href="05-protocol.html">أنشئ البروتوكول</a></div>
'@},
@{File='05-protocol.html';Title='معاينة البروتوكول';Body=@'
<div class="app"><div class="top"><a class="muted" href="04-goals.html">تعديل القيود</a><span class="brand">البروتوكول</span></div><div class="hero"><h1>Deep Technical</h1><p>اخترناه لأن هدفك فهم عميق، ومعك 30 دقيقة يومياً.</p></div><div class="card"><div class="step on"><b>1. معاينة</b> • 3 دقائق</div><div class="step"><b>2. أسئلة</b> • دقيقتان</div><div class="step"><b>3. قراءة مركزة</b> • 20 دقيقة</div><div class="step"><b>4. استرجاع</b> • 5 دقائق</div><div class="step"><b>5. شرح ومراجعة</b> • 8 دقائق</div></div><div class="card"><b>Snapshot v1</b><p class="muted">ستظل جلساتك القديمة مرتبطة بهذه النسخة حتى لو تغيّرت القواعد لاحقاً.</p></div><div class="spacer"></div><a class="btn" href="06-session.html">ابدأ الجلسة</a></div>
'@},
@{File='06-session.html';Title='جلسة التركيز';Body=@'
<div class="app"><div class="top"><span class="muted">الخطوة 3 من 6</span><span class="brand">جلسة التركيز</span></div><div class="card"><b>Clean Architecture</b><p class="muted">صفحة 124 ← 132</p><div class="progress"><span style="width:50%"></span></div></div><div class="timer">18:42</div><div class="hero"><h1>اقرأ بتركيز</h1><p>ابحث عن حدود المكوّنات ولماذا يجب أن تشير التبعيات إلى الداخل.</p></div><div class="row"><a class="btn alt" href="06-session.html">إيقاف مؤقت</a><a class="btn warn" href="06-session.html">سجّل تشتيتاً</a></div><div class="spacer"></div><p class="muted" style="text-align:center">حُفظت حالتك الآن</p><a class="btn" href="07-recall.html">أنهي القراءة وابدأ الاسترجاع</a></div>
'@},
@{File='07-recall.html';Title='الاسترجاع والمراجعة';Body=@'
<div class="app"><div class="top"><span class="muted">لا ترجع للكتاب بعد</span><span class="brand">استرجاع</span></div><div class="hero"><h1>أغلق الصفحة للحظة</h1><p>الذاكرة تقوى عندما تحاول الاسترجاع قبل المراجعة.</p></div><div class="label">ما الفكرة الأساسية؟</div><textarea>اتجاه التبعيات أهم من ترتيب المجلدات…</textarea><div class="label">اشرحها بطريقتك</div><textarea>المكوّن الداخلي لا يعرف تفاصيل الخارج…</textarea><div class="label">ما السؤال المفتوح؟</div><div class="field">كيف نطبق ذلك في extension صغيرة؟</div><div class="spacer"></div><a class="btn" href="08-summary.html">حفظ وإنهاء الجلسة</a></div>
'@},
@{File='08-summary.html';Title='ملخص الجلسة';Body=@'
<div class="app"><div class="top"><span class="muted">حُفظت بنجاح</span><span class="brand">الملخص</span></div><div class="hero"><h1>أحسنت 👏</h1><p>أنهيت جلسة مركزة وأنتجت مخرجات قابلة للمراجعة.</p></div><div class="row"><div class="card"><div class="metric">32</div><span class="muted">دقيقة</span></div><div class="card"><div class="metric">9</div><span class="muted">صفحات</span></div><div class="card"><div class="metric">3</div><span class="muted">مخرجات</span></div></div><div class="card"><b>الفكرة الأهم</b><p>التبعيات تتجه نحو السياسات الأكثر ثباتاً.</p><b>السؤال التالي</b><p>كيف نفصل Adapter قارئ PDF؟</p></div><div class="spacer"></div><a class="btn" href="09-progress.html">عرض تقدم الكتاب</a><a class="btn alt" href="02-library.html">عودة للمكتبة</a></div>
'@},
@{File='09-progress.html';Title='تقدم الكتاب';Body=@'
<div class="app"><div class="top"><a class="muted" href="02-library.html">المكتبة</a><span class="brand">تقدم الكتاب</span></div><div class="hero"><h1>Clean Architecture</h1><p>124 من 350 صفحة</p><div class="progress"><span style="width:35%;background:white"></span></div></div><div class="row"><div class="card"><div class="metric">7</div><span class="muted">جلسات</span></div><div class="card"><div class="metric">3:12</div><span class="muted">ساعات</span></div></div><div class="card"><b>مخرجات التعلم</b><p>12 فكرة • 4 أسئلة مفتوحة • 3 تطبيقات</p></div><div class="card"><b>آخر الجلسات</b><p>اليوم — 9 صفحات — 32 دقيقة</p><p>أمس — 7 صفحات — 28 دقيقة</p></div><div class="spacer"></div><a class="btn" href="06-session.html">ابدأ جلسة جديدة</a><a class="btn alt" href="10-settings.html">الإعدادات والبيانات</a></div>
'@},
@{File='10-settings.html';Title='الإعدادات والبيانات';Body=@'
<div class="app"><div class="top"><a class="muted" href="02-library.html">تم</a><span class="brand">الإعدادات</span></div><div class="card"><b>العرض والوصول</b><div class="label">اللغة</div><div class="field">العربية</div><div class="label">حجم الخط</div><div class="field">110%</div><div class="choice on">✓ تقليل الحركة</div></div><div class="card"><b>الجلسات</b><div class="label">المدة الافتراضية</div><div class="field">30 دقيقة</div></div><div class="card"><b>بياناتك</b><p class="muted">تبقى محلياً على هذا الجهاز.</p><div class="row"><a class="btn alt" href="10-settings.html">تصدير JSON</a><a class="btn alt" href="10-settings.html">استيراد</a></div></div><div class="spacer"></div><a class="btn warn" href="10-settings.html">حذف كل البيانات</a></div>
'@}
)

foreach ($screen in $screens) {
    $html = '<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + $screen.Title + '</title>' + $sharedStyle + '</head><body>' + $screen.Body + '</body></html>'
    Set-Content -LiteralPath (Join-Path $PSScriptRoot $screen.File) -Value $html -Encoding utf8NoBOM
}
